services:
  - type: web
    name: chat-app
    runtime: node
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: .
